[package]
name = "fuel-debugger"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.8"
# fuel-vm = "0.5.1"
fuel-vm = { path = "../fuel-vm-pub-tx", features = ["serde-types", "debug"] }
fuel-types = { version = "0.1", features = ["serde-types"] }
